# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x07\n\x05\x45mpty\"@\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05ready\x18\x03 \x01(\x08\"I\n\x13InstallModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\"9\n\x14InstallModelResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x0fInstallProgress\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\";\n\x0eStatusResponse\x12\x15\n\rworker_status\x18\x01 \x01(\t\x12\x12\n\nlast_error\x18\x02 \x01(\t\";\n\x10InferenceRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x15\n\rinput_payload\x18\x02 \x01(\x0c\";\n\x11InferenceResponse\x12\x16\n\x0eoutput_payload\x18\x01 \x01(\x0c\x12\x0e\n\x06status\x18\x02 \x01(\t2\x84\x02\n\rWorkerControl\x12-\n\x06Health\x12\x0c.agent.Empty\x1a\x15.agent.HealthResponse\x12G\n\x0cInstallModel\x12\x1a.agent.InstallModelRequest\x1a\x1b.agent.InstallModelResponse\x12L\n\x14InstallModelProgress\x12\x1a.agent.InstallModelRequest\x1a\x16.agent.InstallProgress0\x01\x12-\n\x06Status\x12\x0c.agent.Empty\x1a\x15.agent.StatusResponse2I\n\tInference\x12<\n\x07Predict\x12\x17.agent.InferenceRequest\x1a\x18.agent.InferenceResponseB@Z;github.com/itmatzip/itmatzip-agent-go-prototype/proto;proto\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/itmatzip/itmatzip-agent-go-prototype/proto;proto\220\001\001'
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_HEALTHRESPONSE']._serialized_start=31
  _globals['_HEALTHRESPONSE']._serialized_end=95
  _globals['_INSTALLMODELREQUEST']._serialized_start=97
  _globals['_INSTALLMODELREQUEST']._serialized_end=170
  _globals['_INSTALLMODELRESPONSE']._serialized_start=172
  _globals['_INSTALLMODELRESPONSE']._serialized_end=229
  _globals['_INSTALLPROGRESS']._serialized_start=231
  _globals['_INSTALLPROGRESS']._serialized_end=299
  _globals['_STATUSRESPONSE']._serialized_start=301
  _globals['_STATUSRESPONSE']._serialized_end=360
  _globals['_INFERENCEREQUEST']._serialized_start=362
  _globals['_INFERENCEREQUEST']._serialized_end=421
  _globals['_INFERENCERESPONSE']._serialized_start=423
  _globals['_INFERENCERESPONSE']._serialized_end=482
  _globals['_WORKERCONTROL']._serialized_start=485
  _globals['_WORKERCONTROL']._serialized_end=745
  _globals['_INFERENCE']._serialized_start=747
  _globals['_INFERENCE']._serialized_end=820
_builder.BuildServices(DESCRIPTOR, 'agent_pb2', _globals)
# @@protoc_insertion_point(module_scope)
