/** Compact place list: id, ISO 3166-1 alpha-2, IANA zone, English capital/city. */
export const PLACES = [
  { id: "af", cc: "AF", tz: "Asia/Kabul", city: "Kabul" },
  { id: "al", cc: "AL", tz: "Europe/Tirane", city: "Tirana" },
  { id: "dz", cc: "DZ", tz: "Africa/Algiers", city: "Algiers" },
  { id: "ad", cc: "AD", tz: "Europe/Andorra", city: "Andorra la Vella" },
  { id: "ao", cc: "AO", tz: "Africa/Luanda", city: "Luanda" },
  { id: "ag", cc: "AG", tz: "America/Antigua", city: "St. John's" },
  { id: "ar", cc: "AR", tz: "America/Argentina/Buenos_Aires", city: "Buenos Aires" },
  { id: "am", cc: "AM", tz: "Asia/Yerevan", city: "Yerevan" },
  { id: "au", cc: "AU", tz: "Australia/Sydney", city: "Canberra" },
  { id: "at", cc: "AT", tz: "Europe/Vienna", city: "Vienna" },
  { id: "az", cc: "AZ", tz: "Asia/Baku", city: "Baku" },
  { id: "bs", cc: "BS", tz: "America/Nassau", city: "Nassau" },
  { id: "bh", cc: "BH", tz: "Asia/Bahrain", city: "Manama" },
  { id: "bd", cc: "BD", tz: "Asia/Dhaka", city: "Dhaka" },
  { id: "bb", cc: "BB", tz: "America/Barbados", city: "Bridgetown" },
  { id: "by", cc: "BY", tz: "Europe/Minsk", city: "Minsk" },
  { id: "be", cc: "BE", tz: "Europe/Brussels", city: "Brussels" },
  { id: "bz", cc: "BZ", tz: "America/Belize", city: "Belmopan" },
  { id: "bj", cc: "BJ", tz: "Africa/Porto-Novo", city: "Porto-Novo" },
  { id: "bt", cc: "BT", tz: "Asia/Thimphu", city: "Thimphu" },
  { id: "bo", cc: "BO", tz: "America/La_Paz", city: "La Paz" },
  { id: "ba", cc: "BA", tz: "Europe/Sarajevo", city: "Sarajevo" },
  { id: "bw", cc: "BW", tz: "Africa/Gaborone", city: "Gaborone" },
  { id: "br", cc: "BR", tz: "America/Sao_Paulo", city: "Brasília" },
  { id: "bn", cc: "BN", tz: "Asia/Brunei", city: "Bandar Seri Begawan" },
  { id: "bg", cc: "BG", tz: "Europe/Sofia", city: "Sofia" },
  { id: "bf", cc: "BF", tz: "Africa/Ouagadougou", city: "Ouagadougou" },
  { id: "bi", cc: "BI", tz: "Africa/Bujumbura", city: "Gitega" },
  { id: "cv", cc: "CV", tz: "Atlantic/Cape_Verde", city: "Praia" },
  { id: "kh", cc: "KH", tz: "Asia/Phnom_Penh", city: "Phnom Penh" },
  { id: "cm", cc: "CM", tz: "Africa/Douala", city: "Yaoundé" },
  { id: "ca", cc: "CA", tz: "America/Toronto", city: "Ottawa" },
  { id: "cf", cc: "CF", tz: "Africa/Bangui", city: "Bangui" },
  { id: "td", cc: "TD", tz: "Africa/Ndjamena", city: "N'Djamena" },
  { id: "cl", cc: "CL", tz: "America/Santiago", city: "Santiago" },
  { id: "cn", cc: "CN", tz: "Asia/Shanghai", city: "Beijing" },
  { id: "co", cc: "CO", tz: "America/Bogota", city: "Bogotá" },
  { id: "km", cc: "KM", tz: "Indian/Comoro", city: "Moroni" },
  { id: "cg", cc: "CG", tz: "Africa/Brazzaville", city: "Brazzaville" },
  { id: "cd", cc: "CD", tz: "Africa/Kinshasa", city: "Kinshasa" },
  { id: "cr", cc: "CR", tz: "America/Costa_Rica", city: "San José" },
  { id: "hr", cc: "HR", tz: "Europe/Zagreb", city: "Zagreb" },
  { id: "cu", cc: "CU", tz: "America/Havana", city: "Havana" },
  { id: "cy", cc: "CY", tz: "Asia/Nicosia", city: "Nicosia" },
  { id: "cz", cc: "CZ", tz: "Europe/Prague", city: "Prague" },
  { id: "dk", cc: "DK", tz: "Europe/Copenhagen", city: "Copenhagen" },
  { id: "dj", cc: "DJ", tz: "Africa/Djibouti", city: "Djibouti" },
  { id: "dm", cc: "DM", tz: "America/Dominica", city: "Roseau" },
  { id: "do", cc: "DO", tz: "America/Santo_Domingo", city: "Santo Domingo" },
  { id: "ec", cc: "EC", tz: "America/Guayaquil", city: "Quito" },
  { id: "eg", cc: "EG", tz: "Africa/Cairo", city: "Cairo" },
  { id: "sv", cc: "SV", tz: "America/El_Salvador", city: "San Salvador" },
  { id: "gq", cc: "GQ", tz: "Africa/Malabo", city: "Malabo" },
  { id: "er", cc: "ER", tz: "Africa/Asmara", city: "Asmara" },
  { id: "ee", cc: "EE", tz: "Europe/Tallinn", city: "Tallinn" },
  { id: "sz", cc: "SZ", tz: "Africa/Mbabane", city: "Mbabane" },
  { id: "et", cc: "ET", tz: "Africa/Addis_Ababa", city: "Addis Ababa" },
  { id: "fj", cc: "FJ", tz: "Pacific/Fiji", city: "Suva" },
  { id: "fi", cc: "FI", tz: "Europe/Helsinki", city: "Helsinki" },
  { id: "fr", cc: "FR", tz: "Europe/Paris", city: "Paris" },
  { id: "ga", cc: "GA", tz: "Africa/Libreville", city: "Libreville" },
  { id: "gm", cc: "GM", tz: "Africa/Banjul", city: "Banjul" },
  { id: "ge", cc: "GE", tz: "Asia/Tbilisi", city: "Tbilisi" },
  { id: "de", cc: "DE", tz: "Europe/Berlin", city: "Berlin" },
  { id: "gh", cc: "GH", tz: "Africa/Accra", city: "Accra" },
  { id: "gr", cc: "GR", tz: "Europe/Athens", city: "Athens" },
  { id: "gd", cc: "GD", tz: "America/Grenada", city: "St. George's" },
  { id: "gt", cc: "GT", tz: "America/Guatemala", city: "Guatemala City" },
  { id: "gn", cc: "GN", tz: "Africa/Conakry", city: "Conakry" },
  { id: "gw", cc: "GW", tz: "Africa/Bissau", city: "Bissau" },
  { id: "gy", cc: "GY", tz: "America/Guyana", city: "Georgetown" },
  { id: "ht", cc: "HT", tz: "America/Port-au-Prince", city: "Port-au-Prince" },
  { id: "hn", cc: "HN", tz: "America/Tegucigalpa", city: "Tegucigalpa" },
  { id: "hu", cc: "HU", tz: "Europe/Budapest", city: "Budapest" },
  { id: "is", cc: "IS", tz: "Atlantic/Reykjavik", city: "Reykjavík" },
  { id: "in", cc: "IN", tz: "Asia/Kolkata", city: "New Delhi" },
  { id: "id", cc: "ID", tz: "Asia/Jakarta", city: "Jakarta" },
  { id: "ir", cc: "IR", tz: "Asia/Tehran", city: "Tehran" },
  { id: "iq", cc: "IQ", tz: "Asia/Baghdad", city: "Baghdad" },
  { id: "ie", cc: "IE", tz: "Europe/Dublin", city: "Dublin" },
  { id: "il", cc: "IL", tz: "Asia/Jerusalem", city: "Jerusalem" },
  { id: "it", cc: "IT", tz: "Europe/Rome", city: "Rome" },
  { id: "ci", cc: "CI", tz: "Africa/Abidjan", city: "Yamoussoukro" },
  { id: "jm", cc: "JM", tz: "America/Jamaica", city: "Kingston" },
  { id: "jp", cc: "JP", tz: "Asia/Tokyo", city: "Tokyo" },
  { id: "jo", cc: "JO", tz: "Asia/Amman", city: "Amman" },
  { id: "kz", cc: "KZ", tz: "Asia/Almaty", city: "Astana" },
  { id: "ke", cc: "KE", tz: "Africa/Nairobi", city: "Nairobi" },
  { id: "ki", cc: "KI", tz: "Pacific/Tarawa", city: "Tarawa" },
  { id: "kw", cc: "KW", tz: "Asia/Kuwait", city: "Kuwait City" },
  { id: "kg", cc: "KG", tz: "Asia/Bishkek", city: "Bishkek" },
  { id: "la", cc: "LA", tz: "Asia/Vientiane", city: "Vientiane" },
  { id: "lv", cc: "LV", tz: "Europe/Riga", city: "Riga" },
  { id: "lb", cc: "LB", tz: "Asia/Beirut", city: "Beirut" },
  { id: "ls", cc: "LS", tz: "Africa/Maseru", city: "Maseru" },
  { id: "lr", cc: "LR", tz: "Africa/Monrovia", city: "Monrovia" },
  { id: "ly", cc: "LY", tz: "Africa/Tripoli", city: "Tripoli" },
  { id: "li", cc: "LI", tz: "Europe/Vaduz", city: "Vaduz" },
  { id: "lt", cc: "LT", tz: "Europe/Vilnius", city: "Vilnius" },
  { id: "lu", cc: "LU", tz: "Europe/Luxembourg", city: "Luxembourg" },
  { id: "mg", cc: "MG", tz: "Indian/Antananarivo", city: "Antananarivo" },
  { id: "mw", cc: "MW", tz: "Africa/Blantyre", city: "Lilongwe" },
  { id: "my", cc: "MY", tz: "Asia/Kuala_Lumpur", city: "Kuala Lumpur" },
  { id: "mv", cc: "MV", tz: "Indian/Maldives", city: "Malé" },
  { id: "ml", cc: "ML", tz: "Africa/Bamako", city: "Bamako" },
  { id: "mt", cc: "MT", tz: "Europe/Malta", city: "Valletta" },
  { id: "mh", cc: "MH", tz: "Pacific/Majuro", city: "Majuro" },
  { id: "mr", cc: "MR", tz: "Africa/Nouakchott", city: "Nouakchott" },
  { id: "mu", cc: "MU", tz: "Indian/Mauritius", city: "Port Louis" },
  { id: "mx", cc: "MX", tz: "America/Mexico_City", city: "Mexico City" },
  { id: "fm", cc: "FM", tz: "Pacific/Pohnpei", city: "Palikir" },
  { id: "md", cc: "MD", tz: "Europe/Chisinau", city: "Chișinău" },
  { id: "mc", cc: "MC", tz: "Europe/Monaco", city: "Monaco" },
  { id: "mn", cc: "MN", tz: "Asia/Ulaanbaatar", city: "Ulaanbaatar" },
  { id: "me", cc: "ME", tz: "Europe/Podgorica", city: "Podgorica" },
  { id: "ma", cc: "MA", tz: "Africa/Casablanca", city: "Rabat" },
  { id: "mz", cc: "MZ", tz: "Africa/Maputo", city: "Maputo" },
  { id: "mm", cc: "MM", tz: "Asia/Yangon", city: "Naypyidaw" },
  { id: "na", cc: "NA", tz: "Africa/Windhoek", city: "Windhoek" },
  { id: "nr", cc: "NR", tz: "Pacific/Nauru", city: "Yaren" },
  { id: "np", cc: "NP", tz: "Asia/Kathmandu", city: "Kathmandu" },
  { id: "nl", cc: "NL", tz: "Europe/Amsterdam", city: "Amsterdam" },
  { id: "nz", cc: "NZ", tz: "Pacific/Auckland", city: "Wellington" },
  { id: "ni", cc: "NI", tz: "America/Managua", city: "Managua" },
  { id: "ne", cc: "NE", tz: "Africa/Niamey", city: "Niamey" },
  { id: "ng", cc: "NG", tz: "Africa/Lagos", city: "Abuja" },
  { id: "kp", cc: "KP", tz: "Asia/Pyongyang", city: "Pyongyang" },
  { id: "mk", cc: "MK", tz: "Europe/Skopje", city: "Skopje" },
  { id: "no", cc: "NO", tz: "Europe/Oslo", city: "Oslo" },
  { id: "om", cc: "OM", tz: "Asia/Muscat", city: "Muscat" },
  { id: "pk", cc: "PK", tz: "Asia/Karachi", city: "Islamabad" },
  { id: "pw", cc: "PW", tz: "Pacific/Palau", city: "Ngerulmud" },
  { id: "ps", cc: "PS", tz: "Asia/Gaza", city: "Ramallah" },
  { id: "pa", cc: "PA", tz: "America/Panama", city: "Panama City" },
  { id: "pg", cc: "PG", tz: "Pacific/Port_Moresby", city: "Port Moresby" },
  { id: "py", cc: "PY", tz: "America/Asuncion", city: "Asunción" },
  { id: "pe", cc: "PE", tz: "America/Lima", city: "Lima" },
  { id: "ph", cc: "PH", tz: "Asia/Manila", city: "Manila" },
  { id: "pl", cc: "PL", tz: "Europe/Warsaw", city: "Warsaw" },
  { id: "pt", cc: "PT", tz: "Europe/Lisbon", city: "Lisbon" },
  { id: "qa", cc: "QA", tz: "Asia/Qatar", city: "Doha" },
  { id: "ro", cc: "RO", tz: "Europe/Bucharest", city: "Bucharest" },
  { id: "ru", cc: "RU", tz: "Europe/Moscow", city: "Moscow" },
  { id: "rw", cc: "RW", tz: "Africa/Kigali", city: "Kigali" },
  { id: "kn", cc: "KN", tz: "America/St_Kitts", city: "Basseterre" },
  { id: "lc", cc: "LC", tz: "America/St_Lucia", city: "Castries" },
  { id: "vc", cc: "VC", tz: "America/St_Vincent", city: "Kingstown" },
  { id: "ws", cc: "WS", tz: "Pacific/Apia", city: "Apia" },
  { id: "sm", cc: "SM", tz: "Europe/San_Marino", city: "San Marino" },
  { id: "st", cc: "ST", tz: "Africa/Sao_Tome", city: "São Tomé" },
  { id: "sa", cc: "SA", tz: "Asia/Riyadh", city: "Riyadh" },
  { id: "sn", cc: "SN", tz: "Africa/Dakar", city: "Dakar" },
  { id: "rs", cc: "RS", tz: "Europe/Belgrade", city: "Belgrade" },
  { id: "sc", cc: "SC", tz: "Indian/Mahe", city: "Victoria" },
  { id: "sl", cc: "SL", tz: "Africa/Freetown", city: "Freetown" },
  { id: "sg", cc: "SG", tz: "Asia/Singapore", city: "Singapore" },
  { id: "sk", cc: "SK", tz: "Europe/Bratislava", city: "Bratislava" },
  { id: "si", cc: "SI", tz: "Europe/Ljubljana", city: "Ljubljana" },
  { id: "sb", cc: "SB", tz: "Pacific/Guadalcanal", city: "Honiara" },
  { id: "so", cc: "SO", tz: "Africa/Mogadishu", city: "Mogadishu" },
  { id: "za", cc: "ZA", tz: "Africa/Johannesburg", city: "Pretoria" },
  { id: "kr", cc: "KR", tz: "Asia/Seoul", city: "Seoul" },
  { id: "ss", cc: "SS", tz: "Africa/Juba", city: "Juba" },
  { id: "es", cc: "ES", tz: "Europe/Madrid", city: "Madrid" },
  { id: "lk", cc: "LK", tz: "Asia/Colombo", city: "Sri Jayawardenepura Kotte" },
  { id: "sd", cc: "SD", tz: "Africa/Khartoum", city: "Khartoum" },
  { id: "sr", cc: "SR", tz: "America/Paramaribo", city: "Paramaribo" },
  { id: "se", cc: "SE", tz: "Europe/Stockholm", city: "Stockholm" },
  { id: "ch", cc: "CH", tz: "Europe/Zurich", city: "Bern" },
  { id: "sy", cc: "SY", tz: "Asia/Damascus", city: "Damascus" },
  { id: "tj", cc: "TJ", tz: "Asia/Dushanbe", city: "Dushanbe" },
  { id: "tz", cc: "TZ", tz: "Africa/Dar_es_Salaam", city: "Dodoma" },
  { id: "th", cc: "TH", tz: "Asia/Bangkok", city: "Bangkok" },
  { id: "tl", cc: "TL", tz: "Asia/Dili", city: "Dili" },
  { id: "tg", cc: "TG", tz: "Africa/Lome", city: "Lomé" },
  { id: "to", cc: "TO", tz: "Pacific/Tongatapu", city: "Nukuʻalofa" },
  { id: "tt", cc: "TT", tz: "America/Port_of_Spain", city: "Port of Spain" },
  { id: "tn", cc: "TN", tz: "Africa/Tunis", city: "Tunis" },
  { id: "tr", cc: "TR", tz: "Europe/Istanbul", city: "Ankara" },
  { id: "tm", cc: "TM", tz: "Asia/Ashgabat", city: "Ashgabat" },
  { id: "tv", cc: "TV", tz: "Pacific/Funafuti", city: "Funafuti" },
  { id: "ug", cc: "UG", tz: "Africa/Kampala", city: "Kampala" },
  { id: "ua", cc: "UA", tz: "Europe/Kyiv", city: "Kyiv" },
  { id: "ae", cc: "AE", tz: "Asia/Dubai", city: "Abu Dhabi" },
  { id: "gb", cc: "GB", tz: "Europe/London", city: "London" },
  { id: "us", cc: "US", tz: "America/New_York", city: "Washington, D.C." },
  { id: "us-ny", cc: "US", tz: "America/New_York", city: "New York" },
  { id: "us-chicago", cc: "US", tz: "America/Chicago", city: "Chicago" },
  { id: "us-denver", cc: "US", tz: "America/Denver", city: "Denver" },
  { id: "us-la", cc: "US", tz: "America/Los_Angeles", city: "Los Angeles" },
  { id: "us-honolulu", cc: "US", tz: "Pacific/Honolulu", city: "Honolulu" },
  { id: "uy", cc: "UY", tz: "America/Montevideo", city: "Montevideo" },
  { id: "uz", cc: "UZ", tz: "Asia/Tashkent", city: "Tashkent" },
  { id: "vu", cc: "VU", tz: "Pacific/Efate", city: "Port Vila" },
  { id: "va", cc: "VA", tz: "Europe/Rome", city: "Vatican City" },
  { id: "ve", cc: "VE", tz: "America/Caracas", city: "Caracas" },
  { id: "vn", cc: "VN", tz: "Asia/Ho_Chi_Minh", city: "Hanoi" },
  { id: "ye", cc: "YE", tz: "Asia/Aden", city: "Sana'a" },
  { id: "zm", cc: "ZM", tz: "Africa/Lusaka", city: "Lusaka" },
  { id: "zw", cc: "ZW", tz: "Africa/Harare", city: "Harare" },
  { id: "tw", cc: "TW", tz: "Asia/Taipei", city: "Taipei" },
  { id: "hk", cc: "HK", tz: "Asia/Hong_Kong", city: "Hong Kong" },
  { id: "mo", cc: "MO", tz: "Asia/Macau", city: "Macau" },
  { id: "xk", cc: "XK", tz: "Europe/Belgrade", city: "Pristina" },
  { id: "utc", cc: "", tz: "UTC", city: "UTC" },
];

export const LEGACY_IDS = {
  seoul: "kr",
  tokyo: "jp",
  beijing: "cn",
  hongkong: "hk",
  taipei: "tw",
  singapore: "sg",
  bangkok: "th",
  dubai: "ae",
  mumbai: "in",
  sydney: "au",
  london: "gb",
  paris: "fr",
  berlin: "de",
  moscow: "ru",
  newyork: "us-ny",
  chicago: "us-chicago",
  losangeles: "us-la",
  toronto: "ca",
  saopaulo: "br",
  utc: "utc",
};
