"""Backward-compatible re-exports — use engines.codeformer_runtime."""

from engines.codeformer_runtime import (  # noqa: F401
    CODEFORMER_PIP_PACKAGES,
    DEFAULT_CODEFORMER_SOURCE_ZIP_URL,
    DEFAULT_CODEFORMER_WEIGHT_URL,
    DEFAULT_REALESRGAN_WEIGHT_URL,
    DEFAULT_WHEELS_CPU_URL,
    DEFAULT_WHEELS_GPU_PART_URLS,
    IMAGE_ENHANCER_LIB_BASE,
    ensure_venv,
    ensure_wheels_bundle_extracted,
    has_nvidia_gpu,
    install_basicsr_develop,
    install_pip_packages,
    install_pip_packages_from_wheels,
    install_pytorch,
    install_pytorch_from_wheels,
    install_runtime_dependencies,
    is_cuda_available,
    is_pip_stack_ready,
    is_torch_installed,
    is_venv_ready,
    is_venv_ready_fast,
    probe_torch,
    select_torch_bundle,
    venv_python,
    installed_torch_version,
    installed_torch_variant,
    invalidate_torch_probe_cache,
)
